"""
Historical prototype from a marketplace automation project.

This file has been sanitized for public release. Credentials and
account-specific configuration have been removed.

It is preserved to document the original implementation and development
process rather than as an example of production-ready code.
"""

import os
import csv

from ebaysdk.trading import Connection as Trading
from ebaysdk.exception import ConnectionError

from product_lookup import get_card_info


# Paths and configurations
project_root = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..")
)

config_folder = os.path.join(project_root, ".config")
config_file = os.path.join(config_folder, "ebay.yaml")

# CSV file generated by the inventory ingestion workflow
csv_files_folder = os.path.join(project_root, "csv_files")
csv_file_path = os.path.join(
    csv_files_folder,
    "cards_from_pics.csv"
)


def add_fixed_price_item(
    card_name,
    set_code,
    price,
    quantity,
    rarity=None,
    image_url=None
):
    """
    Creates a fixed-price eBay listing for a specified trading card.
    """

    # Retrieve and normalize product metadata
    card_details = get_card_info(
        card_name,
        set_code,
        rarity
    )

    if not card_details:
        print(
            f"Failed to retrieve card details for "
            f"{card_name} with set code {set_code}"
        )
        return

    try:
        # Initialize eBay Trading API connection
        api = Trading(
            config_file=config_file,
            warnings=True,
            debug=True,
            siteid="2"
        )

        # Construct marketplace item specifics
        item_specifics = [
            {
                "Name": "Game",
                "Value": "Yu-Gi-Oh! TCG"
            },
            {
                "Name": "Card Type",
                "Value": card_details.get(
                    "card_type",
                    "Trading Card"
                )
            },
            {
                "Name": "Card Name",
                "Value": card_details["name"]
            },
            {
                "Name": "Features",
                "Value": card_details["edition"]
            },
            {
                "Name": "Rarity",
                "Value": card_details["rarity"]
            },
            {
                "Name": "Attribute",
                "Value": card_details.get(
                    "attribute",
                    "N/A"
                )
            },
            {
                "Name": "Manufacturer",
                "Value": "Konami"
            }
        ]

        description = (
            f"This is a {card_details['rarity']} "
            f"{card_details['name']} from the "
            f"{card_details['set_name']} set. "
            f"Perfect for collectors!"
        )

        # Construct eBay listing payload
        item = {
            "Title": (
                f"{card_details['name']} - "
                f"{set_code} - "
                f"{card_details['rarity']} - "
                f"{card_details['edition']} - "
                f"Near Mint"
            ),
            "Description": description,
            "PrimaryCategory": {
                "CategoryID": "183454"
            },
            "StartPrice": price,
            "Currency": "CAD",
            "Country": "CA",
            "DispatchTimeMax": 3,
            "ListingDuration": "GTC",
            "ListingType": "FixedPriceItem",
            "Location": "Ontario, Canada",
            "Quantity": quantity,
            "ConditionID": 4000,
            "ConditionDescriptors": {
                "ConditionDescriptor": {
                    "Name": "40001",
                    "Value": "400010"
                }
            },

            # Account-specific profile IDs removed
            "SellerProfiles": {
                "SellerPaymentProfile": {
                    "PaymentProfileID":
                        "YOUR_PAYMENT_PROFILE_ID"
                },
                "SellerReturnProfile": {
                    "ReturnProfileID":
                        "YOUR_RETURN_PROFILE_ID"
                },
                "SellerShippingProfile": {
                    "ShippingProfileID":
                        "YOUR_SHIPPING_PROFILE_ID"
                }
            },

            "ItemSpecifics": {
                "NameValueList": item_specifics
            },

            "PictureDetails": {
                "PictureURL": image_url
            }
        }

        # Submit listing through the eBay Trading API
        response = api.execute(
            "AddFixedPriceItem",
            {"Item": item}
        )

        print(
            f"Listing created for {card_name} "
            f"(Set Code: {set_code})"
        )

        print(response.dict())

    except ConnectionError as e:
        print(f"Error: {e}")

        if e.response:
            print("Response Error Details:")
            print(e.response.dict())


def create_listings_from_csv(csv_file_path):
    """
    Reads inventory records from CSV and creates an eBay listing
    for each row.
    """

    with open(csv_file_path, mode="r") as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:
            try:
                card_name = row["card_name"]
                set_code = row["set_code"]

                rarity = (
                    row["rarity"]
                    if row["rarity"] != "X"
                    else None
                )

                price = (
                    float(row["price"])
                    if row["price"] != "X"
                    else 0.0
                )

                quantity = (
                    int(row["quantity"])
                    if row["quantity"] != "X"
                    else 1
                )

                image_url = row["URL"]

            except ValueError:
                print(
                    "Skipping row with invalid "
                    f"price or quantity: {row}"
                )
                continue

            print(
                f"Preparing to list: {card_name}, "
                f"Set Code: {set_code}, "
                f"Price: {price}, "
                f"Quantity: {quantity}, "
                f"Rarity: {rarity}"
            )

            add_fixed_price_item(
                card_name,
                set_code,
                price,
                quantity,
                rarity,
                image_url
            )


# Run batch listing workflow
create_listings_from_csv(csv_file_path)
